defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_
  
scheduler:
  decay_rate: 0.95
  decay_steps: 500

training:
  rec_validation_freq: 100
  rec_inference_freq: 100
  rec_monitor_freq: 100
  rec_constraint_freq: 100
  max_steps : 1000

batch_size:
  Interior: 4096
  IC: 2048
  BC: 2048

graph:
  func_arch: true
